function x= ploting(meas)
figure; grid on; hold on;
sgtitle('Accelerometer')
subplot(3,1,1)
histogram(meas.acc(1, ~any(isnan(meas.acc))),50, Normalization="pdf")
xlabel('time step')
ylabel('$x_{acc}$', Interpreter='latex')
subplot(3,1,2)
histogram(meas.acc(2, ~any(isnan(meas.acc))),50, Normalization="pdf")
xlabel('time step')
ylabel('$y_{acc}$', Interpreter='latex')
subplot(3,1,3)
histogram(meas.acc(3, ~any(isnan(meas.acc))),50, Normalization="pdf")
xlabel('time step')
ylabel('$z_{acc}$', Interpreter='latex')


figure; grid on; hold on;
sgtitle('Gyro')
subplot(3,1,1)
histogram(meas.gyr(1, ~any(isnan(meas.gyr))),50, Normalization="pdf")
xlabel('time step')
ylabel('$\omega_x$', Interpreter='latex')
subplot(3,1,2)
histogram(meas.gyr(2, ~any(isnan(meas.gyr))),50, Normalization="pdf")
xlabel('time step')
ylabel('$\omega_y$', Interpreter='latex')
subplot(3,1,3)
histogram(meas.gyr(3, ~any(isnan(meas.gyr))),50, Normalization="pdf")
xlabel('time step')
ylabel('$\omega_z$', Interpreter='latex')

figure; hold on;
sgtitle('Magnetometer')
subplot(3,1,1)
histogram(meas.mag(1, ~any(isnan(meas.mag))),50, Normalization="pdf")
xlabel('time step')
ylabel('$mag_x$', Interpreter='latex')
subplot(3,1,2)
histogram(meas.mag(2, ~any(isnan(meas.mag))),50, Normalization="pdf")
xlabel('time step')
ylabel('$mag_y$', Interpreter='latex')
subplot(3,1,3)
histogram(meas.mag(3, ~any(isnan(meas.mag))),50, Normalization="pdf")
xlabel('time step')
ylabel('$mag_z$', Interpreter='latex')

figure; grid on;hold on;
plot(meas.t, meas.acc(1,:))
plot(meas.t, meas.acc(2,:))
plot(meas.t, meas.acc(3,:))
xlabel('time step')
ylabel('Accleration')
title('Acclerometer signal')
legend({'Acc x', 'Acc y', 'Acc z'})

figure; grid on;hold on;
plot(meas.t, meas.gyr(1,:))
plot(meas.t, meas.gyr(2,:))
plot(meas.t, meas.gyr(3,:))
xlabel('time step')
ylabel('Angular velocity')
title('Gyro signal')
legend({'Gyro x', 'Gyro y', 'Gyro z'})

figure; grid on;hold on;
plot(meas.t, meas.mag(1,:))
plot(meas.t, meas.mag(2,:))
plot(meas.t, meas.mag(3,:))
xlabel('time step')
ylabel('Magnetometer')
title('Magnetometer signal')
legend({'Mag x', 'Mag y', 'Mag z'})
end